
development: &dev
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: <%= ENV['CPONTO_DB_NAME']  %>
  username: <%= ENV['CPONTO_DB_USER'] %>
  password: <%= ENV['CPONTO_DB_PASS'] %>
  host: <%= ENV['CPONTO_DB_HOST'] %>
  port: <%= ENV['CPONTO_DB_PORT'] %>

production: 
  <<: *dev

test: 
  <<: *dev
