require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PontosController do

  # This should return the minimal set of attributes required to create a valid
  # Ponto. As you add validations to Ponto, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "ano" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PontosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all pontos as @pontos" do
      ponto = Ponto.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pontos).should eq([ponto])
    end
  end

  describe "GET show" do
    it "assigns the requested ponto as @ponto" do
      ponto = Ponto.create! valid_attributes
      get :show, {:id => ponto.to_param}, valid_session
      assigns(:ponto).should eq(ponto)
    end
  end

  describe "GET new" do
    it "assigns a new ponto as @ponto" do
      get :new, {}, valid_session
      assigns(:ponto).should be_a_new(Ponto)
    end
  end

  describe "GET edit" do
    it "assigns the requested ponto as @ponto" do
      ponto = Ponto.create! valid_attributes
      get :edit, {:id => ponto.to_param}, valid_session
      assigns(:ponto).should eq(ponto)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ponto" do
        expect {
          post :create, {:ponto => valid_attributes}, valid_session
        }.to change(Ponto, :count).by(1)
      end

      it "assigns a newly created ponto as @ponto" do
        post :create, {:ponto => valid_attributes}, valid_session
        assigns(:ponto).should be_a(Ponto)
        assigns(:ponto).should be_persisted
      end

      it "redirects to the created ponto" do
        post :create, {:ponto => valid_attributes}, valid_session
        response.should redirect_to(Ponto.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ponto as @ponto" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ponto.any_instance.stub(:save).and_return(false)
        post :create, {:ponto => { "ano" => "invalid value" }}, valid_session
        assigns(:ponto).should be_a_new(Ponto)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ponto.any_instance.stub(:save).and_return(false)
        post :create, {:ponto => { "ano" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ponto" do
        ponto = Ponto.create! valid_attributes
        # Assuming there are no other pontos in the database, this
        # specifies that the Ponto created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ponto.any_instance.should_receive(:update).with({ "ano" => "1" })
        put :update, {:id => ponto.to_param, :ponto => { "ano" => "1" }}, valid_session
      end

      it "assigns the requested ponto as @ponto" do
        ponto = Ponto.create! valid_attributes
        put :update, {:id => ponto.to_param, :ponto => valid_attributes}, valid_session
        assigns(:ponto).should eq(ponto)
      end

      it "redirects to the ponto" do
        ponto = Ponto.create! valid_attributes
        put :update, {:id => ponto.to_param, :ponto => valid_attributes}, valid_session
        response.should redirect_to(ponto)
      end
    end

    describe "with invalid params" do
      it "assigns the ponto as @ponto" do
        ponto = Ponto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ponto.any_instance.stub(:save).and_return(false)
        put :update, {:id => ponto.to_param, :ponto => { "ano" => "invalid value" }}, valid_session
        assigns(:ponto).should eq(ponto)
      end

      it "re-renders the 'edit' template" do
        ponto = Ponto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ponto.any_instance.stub(:save).and_return(false)
        put :update, {:id => ponto.to_param, :ponto => { "ano" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ponto" do
      ponto = Ponto.create! valid_attributes
      expect {
        delete :destroy, {:id => ponto.to_param}, valid_session
      }.to change(Ponto, :count).by(-1)
    end

    it "redirects to the pontos list" do
      ponto = Ponto.create! valid_attributes
      delete :destroy, {:id => ponto.to_param}, valid_session
      response.should redirect_to(pontos_url)
    end
  end

end
